language: node_js
sudo: false
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9

os:
  - linux
  - osx
script:
  - npm test
  # make sure when the docs are generated nothing changes (a.k.a. the docs have already been generated)
  - npm run gendocs
  - npm run after-travis "Make sure to generate docs!"
after_success:
  - npm run codecov -- -f coverage/lcov.info

notifications:
  email: false
