environment:
  matrix:
    - nodejs_version: '9'
    - nodejs_version: '8'
    - nodejs_version: '7'
    - nodejs_version: '6'
    - nodejs_version: '5'
    - nodejs_version: '4'

version: '{build}'

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
  - npm run ci-or-install

matrix:
  fast_finish: false

# No need for MSBuild on this project
build: off

test_script:
  - npm test

on_success:
  - npm run codecov -- -f coverage/lcov.info
