environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '5'
    - nodejs_version: '4'

version: '{build}'

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
  - npm install

matrix:
  fast_finish: true

# No need for MSBuild on this project
build: off

test_script:
  - npm test
